name: hooked
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.3.0
  get: ^4.6.5
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  firebase_auth_web: ^5.13.5
  js: ^0.7.1
  firebase_database: ^11.2.0
  cloud_firestore: ^5.6.0
  flutter_dotenv: ^5.0.3
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0
  http: ^1.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  file_picker: ^5.0.1
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hooked_icon-removebg-preview.png
    - .env
